### ISSUE TITLE
Reusing Options

### ISSUE THREAD

**Issue by jlandahl** [frysztak/normalize-url-rs#1]
I just started playing around with the library, and noticed that the `normalize_url` function takes ownership of the `Options` parameter. If it only borrowed the options instead it would be trivial to re-use an `Options` object for each call to `normalize_url`. My first thought was to `.clone()` my `Options` object, but then it doesn't implement `Clone`. So in its current state it looks like you have to create a new `Options` object over and over, which shouldn't be necessary.

I'll take a stab at this and submit a PR shortly.

**Comment by frysztak** [comment]
thanks for bringing it up, and thanks for submitting the PR. in v0.2.0 options are borrowed :tada:
